### ISSUE TITLE
Address class question

### ISSUE THREAD

**Issue by BobSelf** [mfncooper/pyham_ax25#3]
I'm testing the Address class and finding that the last byte of the 7 byte addresses are difftent than what this ax.25 generator is producing:

https://notblackmagic.com/bitsnpieces/ax.25/

Why are they different? Heres the test code:

dest = 'NJ7P'
ssid = 0
addr = ax25.Address(dest, ssid)
b = addr.pack()

src = 'N7LEM'
ssid = 0
addr = ax25.Address(src, ssid)
b = addr.pack()

the results:

NJ7P-0 -->    9c  94  6e  a0  40  40  00
N7LEM-0 --> 9c  6e  98  8a  9a  40  00

I think that the ax.25 spec uses this same example and agrees with the generator.

**Comment by mfncooper** [comment]
There are two reasons you're seeing a difference.

1. The generator, by default, sets the command/response bit in the first address. (The first drop-down, "Type (AX.25 V2)", is set to Command.) This affects the top bit in the last byte of the first address. This bit needs to be set explicitly on an ax25.Address, because only the caller knows the intended usage. You can set this using the ``command_response`` property of the ``ax25.Address``.

2. The ``pack()`` method is not setting the reserved bits (bits 5 & 6 of the last byte). The AX.25 spec does say "When not implemented, they are set to 1", so this is a bug in the ``ax25`` package that I'll fix shortly. Thanks for spotting that. That said, I've never seen any software that pays any attention to those bits, so their not being set shouldn't cause any issues.
